### ISSUE TITLE
Scrapes do not timeout quickly after the context expires

### ISSUE THREAD

**Issue by gebn** [gebn/bmc_exporter#13]
Given a 8s timeout, requests can take >11s. This can be mitigated by setting a higher `scrape_timeout`, but should not be necessary.

**Comment by gebn** [comment]
They do; the problem is the timeout isn't started at the beginning of the request! First we check the target param exists, then we look up the handler (which can block), then we send a message to the handler (which can block), then we finally start the timer. It varies because sometimes we get lucky and the block is short; sometimes it is ~3s.

**Comment by gebn** [comment]
There are several problems here:

 - Looking up the handler takes an unknown amount of time; by the time we've got the lock, we may have to return immediately, which is wasteful. We might as well create it for next time at this point to make progress and not have to halt all requests again in 30s (or less with multiple scrapers).
 - Once the handler has been obtained, we need to send it the request down a channel as part of serialising requests to a given BMC, which may block indefinitely. The best we can do is check the context on read, before delegating to Prometheus's `ServeHTTP()` for the registry, as there is no option that accepts a context.
 - Similarly, there is no way to pass a context into the `Collect()` method.

This would be somewhat mitigated if we created a fresh handler for each request, but we couldn't create a fresh `Collect()` without losing the exclusive access guarantee. Moving that out of `Collect()` would move the problem elsewhere, as the request would still breach the timeout if the lock or channel send took too long.

The `Timeout` `HandlerOpts` option is useless with one `Collector`, as we may as well implement this within the `Collect()` method and be able to return a partial response. The issue is `Collect()` may only be called several seconds into the request.

Timeouts happen when multiple scrapers hit the same exporter for a non-responsive BMC simultaneously. The first one gets through and blocks for 8s or so, then the next one gets through and only has 7s before it times out. The third one times out before we've even got to `Collect()`. In general, timeouts need to be made much shorter to cope with this. We should also recommend a `scrape_timeout` of 30s.

**Comment by gebn** [comment]
Hacky, but possibly workable solution: have a `Collector` implementation with a public `Context` field, which is set to `context.WithTimeout(req.Context(), config.Timeout)` before we call `ServeHTTP()` on the handler returned by `HandlerFor()`.

**Comment by lukeyeager** [comment]
Thanks for documenting your decisions!

I see that the client library is unlikely to allow passing a context soon: https://github.com/prometheus/client_golang/issues/228#issuecomment-475214970

I'm curious whether you still like your design? If I'm reading correctly ... ServeHTTP sends the request to a channel which is received in eventLoop which sticks ctx into the collector singleton before calling handler.ServeHTTP which in turn calls Collect which finally gets to use the stored ctx. I'm working on similar exporters and am realizing I need to solve the same problem. I expect your solution is robust but I was hoping to find a simpler one.
